version: "3.8"

#NETWORK
networks:
  my-network:
    driver: bridge

#VOLUMES
volumes:
  dir-site:
    driver_opts:
      device: /Volumes/Data/mycode/compose1/sites
      o: bind
      type: nfs

#SERVICES
services:
  nginx:
    container_name: nginx-product
    image: nginx:alpine
    restart: always
    hostname: nginx
    networks:
      - my-network
    volumes:
      - dir-site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80

  php:
    container_name: php-product
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/var/www/html
      - ./php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini

  mysql:
    container_name: mysql-product
    image: "mysql:latest"
    hostname: mysql
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - ./env/mysql.env
